# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  # "iPhone 8 Plus",
  "iPhone XS"
])
apps = JSON.parse(ENV["SCREENSHOTS_JSON"])["appParams"]
languages(apps[ENV["APP"]]["languages"])

scheme = ENV["APPSCHEME"]

# The name of the scheme which contains the UI Tests
# scheme("SchemeName")

# Where should the resulting screenshots be stored?
output_directory("./screenshots/#{scheme}/")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(false)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
